local _, ns = ...
local Registry = ns:GetModule("Encounters.Registry")

Registry:Register({
    key = "altar",
    name = "The Coiled Altar",
    encounterID = 3429,
    strategyStatus = "12.1 Heroic plan: PTR-video + Journal reviewed 2026-08-13; live pending",
    explanation = {
        "P1: TANK AIM SEVER THROUGH VENOM. RAID STAYS OUT OF THE FRONTAL.",
        "GUILLOTINE: TEAM A/B ALTERNATE 5+ SOAKS. THEN RAID MOVES 40+ YARDS FROM THE AXE.",
        "P2: BREAK DREADMARCH SHIELDS. FIXATED PLAYERS FACE THEIR MANIFESTATIONS.",
        "TANK AIM SOUL SEVER THROUGH MANIFESTATIONS. RAID CLEARS THE FRONTAL.",
        "NIGHTFALL: BREAK SHIELD, THEN INTERRUPT. SPIRITCACKLE: KILL ADDS AND KICK WAIL.",
        "GLOOMBOMB TARGETS 15+ YARDS OUT. IF GRAVEBOUND, RECLAIM YOUR SOUL FRAGMENT.",
        "SOULBINDING: STOMP 1 FRAGMENT AT A TIME, SPACE STOMPS 2+ SEC, NONE REACH ZUL'JAN.",
        "FINAL: KEEP BOTH BOSSES EVEN AND KILL THEM TOGETHER.",
    },
    calls = {
        {
            key = "sever",
            ability = "Sever",
            action = "Tank through venom > raid clear frontal",
            warning = "SEVER > TANK AIM THROUGH VENOM > RAID CLEAR FRONT",
            voice = "Sever",
            spellIDs = { 1299680 },
        },
        {
            key = "guillotine",
            ability = "Guillotine",
            action = "Next 5+ team soak > then 40+ from axe",
            warning = "GUILLOTINE > NEXT 5+ TEAM SOAK > THEN RAID 40+ FROM AXE",
            voice = "Guillotine",
            spellIDs = { 1283489, 1283485, 1299266 },
            timerNames = { "Guillotine", "Grim Guillotine" },
        },
        {
            key = "dreadmarch",
            ability = "Dreadmarch",
            action = "Break shields > fixates face ghosts",
            warning = "DREADMARCH > BREAK SHIELDS > FIXATES FACE GHOSTS",
            voice = "Dreadmarch",
            spellIDs = { 1289900 },
        },
        {
            key = "nightfall",
            ability = "Eternal Nightfall",
            action = "Break shield > interrupt",
            warning = "ETERNAL NIGHTFALL > BREAK SHIELD > INTERRUPT",
            voice = "Nightfall",
            spellIDs = { 1286918 },
        },
        {
            key = "spiritcackle",
            ability = "Spiritcackle",
            action = "Kill Soulcoilers > interrupt Wail",
            warning = "SPIRITCACKLE > KILL SOULCOILERS > INTERRUPT WAIL",
            voice = "Add",
            spellIDs = { 1286441 },
        },
        {
            key = "gloombomb",
            ability = "Gloombomb",
            action = "Targets 15+ out > reclaim fragment",
            warning = "GLOOMBOMB > TARGETS 15+ OUT > RECLAIM SOUL FRAGMENT",
            voice = "Bomb",
            spellIDs = { 1286895 },
        },
        {
            key = "intermission",
            ability = "Soulbinding",
            action = "Stomp one fragment at a time",
            warning = "SOULBINDING > STOMP 1 FRAGMENT AT A TIME > SPACE STOMPS 2+ SEC",
            voice = "Fragments",
            timing = false,
        },
        {
            key = "final",
            ability = "Final Phase",
            action = "Balance both > kill together",
            warning = "FINAL PHASE > KEEP BOTH EVEN > KILL TOGETHER",
            voice = "Final phase",
            timing = false,
            iconSpellID = 1298381,
        },
    },
})
