local _, ns = ...
local Registry = ns:GetModule("Encounters.Registry")

Registry:Register({
    key = "explorers",
    name = "The Lost Explorers",
    encounterID = 3497,
    strategyStatus = "12.1 Heroic plan: YouTube-guide + Journal reviewed 2026-08-13; live pending",
    explanation = {
        "HEROIC: TANK NAMA + GEBBO TOGETHER. KEEP IKU 30+ YARDS AWAY.",
        "KILL ORDER: NAMA FIRST, IKU SECOND, GEBBO LAST.",
        "ASSIGNED CRATE BREAKERS STOMP BOXES BEFORE 25 SEC. ROTATE TO LIMIT SPLINTERS.",
        "FINAL ASCENSION: FEED A FISH TO THE CONTROLLED TORTOLLAN BEFORE THE CAST ENDS.",
        "MIGHTY THUD: 3 TARGETS EACH GO TO A SOAK GROUP, THEN MOVE OUT OF AFTERSHOCK.",
        "BLINK NOVA TARGET GOES TO THE EDGE. EVERYONE ELSE MOVES FAR AWAY.",
        "ICEBOUND FLAMES: INTERRUPT. FIRE CLEARS FROST; FROST CLEARS FIRE.",
        "TANKS: SWAP AS STEADY STRIKES AND SHREDDING SHARDS BECOME DANGEROUS.",
    },
    calls = {
        {
            key = "killorder",
            ability = "Kill Order",
            action = "Nama > Iku > Gebbo",
            warning = "KILL ORDER > NAMA FIRST > IKU SECOND > GEBBO LAST",
            voice = "Kill order",
            timing = false,
        },
        {
            key = "crates",
            ability = "Throw Junk",
            action = "Assigned breakers stomp crates > get fish",
            warning = "CRATES > ASSIGNED BREAKERS STOMP THEM > GET FISH",
            voice = "Crates",
            timing = false,
        },
        {
            key = "fish",
            ability = "Final Ascension",
            action = "Feed fish to controlled tortollan",
            warning = "FINAL ASCENSION > FEED FISH TO CONTROLLED TORTOLLAN NOW",
            voice = "Fish",
            timing = false,
            iconSpellID = 1292779,
        },
        {
            key = "thud",
            ability = "Mighty Thud",
            action = "3 targets > each target to soak group",
            warning = "MIGHTY THUD > 3 TARGETS > EACH TARGET TO A SOAK GROUP",
            voice = "Soak",
            spellIDs = { 1296092 },
        },
        {
            key = "blink",
            ability = "Blink Nova",
            action = "Target edge > raid move away",
            warning = "BLINK NOVA > TARGET EDGE > RAID MOVE AWAY",
            voice = "Move away",
            spellIDs = { 1290711 },
        },
        {
            key = "icebound",
            ability = "Icebound Flames",
            action = "Interrupt now",
            warning = "ICEBOUND FLAMES > INTERRUPT NOW",
            voice = "Interrupt",
            spellIDs = { 1286921 },
        },
    },
})
