local _, ns = ...
local Registry = ns:GetModule("Encounters.Registry")

Registry:Register({
    key = "nekzali",
    name = "Nek'zali the Soulcoiler",
    encounterID = 3470,
    strategyStatus = "12.1 source-reviewed; live Heroic pending",
    explanation = {
        "STAY OUT OF THE WELL. NOTHING REACHES IT.",
        "P1: ADDS > BOSS. REND OUT. CLEAR THE TANK LINE.",
        "50%: KILL ECHOES. PYRE SOAKS BURN CORPSES.",
        "P2: LUST + BURN. DODGE MOVING PUDDLES.",
    },
    calls = {
        {
            key = "adds",
            ability = "Restless Amani",
            action = "Break shields > kill before Well",
            warning = "ADDS > BREAK SHIELDS > KILL BEFORE WELL",
            voice = "Adds",
            spellIDs = { 1295397, 1297630 },
        },
        {
            key = "rend",
            ability = "Essence Rend",
            action = "Targets out > dispel outside",
            warning = "REND > TARGETS OUT > DISPEL OUTSIDE",
            voice = "Rend",
            spellIDs = { 1287426 },
        },
        {
            key = "barrage",
            ability = "Possession Barrage",
            action = "Tank out > clear tank line",
            warning = "BARRAGE > TANK OUT > CLEAR TANK LINE",
            voice = "Barrage",
            spellIDs = { 1292036, 1284103 },
        },
        {
            key = "ignition",
            ability = "Soulcoil Ignition",
            action = "Healing CD > dodge",
            warning = "IGNITION > HEALING CD > DODGE",
            voice = "Ignition",
            spellIDs = { 1285681 },
        },
        {
            key = "echoes",
            ability = "Echoes of Jawae",
            action = "Kill Echoes > break Tethers",
            warning = "ECHOES > KILL NOW > BREAK TETHERS",
            voice = "Echoes",
            spellIDs = { 1289696 },
            timerNames = { "Tether of Awakening" },
        },
        {
            key = "pyre",
            ability = "Hungering Pyre",
            action = "Soak > flames burn corpses",
            warning = "PYRE > SOAK > FLAMES BURN CORPSES",
            voice = "Pyre",
            spellIDs = { 1305421, 1290679 },
        },
        {
            key = "phase2",
            ability = "Phase 2",
            action = "Lust + DPS CDs > burn",
            warning = "PHASE 2 > LUST + DPS CDS > BURN",
            voice = "Phase two",
            timing = false,
            iconSpellID = 1299673,
        },
    },
})
