local _, ns = ...
local Registry = ns:GetModule("Encounters.Registry")

Registry:Register({
    key = "nekzali",
    name = "Nek'zali the Soulcoiler",
    encounterID = 3470,
    strategyStatus = "12.1 PTR source-reviewed 2026-08-13; live Heroic pending",
    explanation = {
        "NEVER ENTER THE WELL. NEVER LET ADDS REACH IT.",
        "ADDS: BREAK THEIR SHIELDS, THEN KILL THEM BEFORE THE WELL.",
        "REND TARGETS: MOVE OUT. A CULTIST SPAWNS WHERE YOU END.",
        "BARRAGE: TANK MOVE FAR. EVERYONE ELSE CLEAR THE TANK LINE.",
        "50%: KILL ECHOES TO BREAK THE TETHERS.",
        "PYRE: ASSIGNED SOAKERS IN. NON-SOAKERS GET FLAME.",
        "FLAME TARGETS: MOVE TO AMANI REMAINS BEFORE THE FLAME EXPIRES.",
        "PHASE 2: LUST AND BURN THE BOSS.",
    },
    calls = {
        {
            key = "adds",
            ability = "Restless Amani",
            action = "Break shields > kill before Well",
            warning = "ADDS > BREAK SHIELDS > KILL BEFORE WELL",
            voice = "Adds",
            spellIDs = { 1295397, 1297630 },
        },
        {
            key = "rend",
            ability = "Essence Rend",
            action = "Targets out > drop Cultists away",
            warning = "REND > TARGETS MOVE OUT > DROP CULTISTS AWAY",
            voice = "Rend",
            spellIDs = { 1287426 },
        },
        {
            key = "barrage",
            ability = "Possession Barrage",
            action = "Tank far > clear tank line",
            warning = "BARRAGE > TANK FAR > RAID CLEAR THE LINE",
            voice = "Barrage",
            spellIDs = { 1292036, 1284103 },
        },
        {
            key = "ignition",
            ability = "Soulcoil Ignition",
            action = "Healing CD > dodge impacts",
            warning = "IGNITION > HEALING CD > DODGE IMPACTS",
            voice = "Ignition",
            spellIDs = { 1285681 },
        },
        {
            key = "echoes",
            ability = "Echoes of Jawae",
            action = "Kill Echoes > break Tethers",
            warning = "ECHOES > KILL THEM > BREAK TETHERS",
            voice = "Echoes",
            spellIDs = { 1289696 },
            timerNames = { "Tether of Awakening" },
        },
        {
            key = "pyre",
            ability = "Hungering Pyre",
            action = "Soakers in > flames move to remains",
            warning = "PYRE > SOAKERS IN > FLAME TARGETS MOVE TO AMANI REMAINS",
            voice = "Pyre",
            spellIDs = { 1305421, 1290679 },
        },
        {
            key = "phase2",
            ability = "Phase 2",
            action = "Lust > burn boss",
            warning = "PHASE 2 > LUST > BURN BOSS",
            voice = "Phase two",
            timing = false,
            iconSpellID = 1299673,
        },
    },
})
