local _, ns = ...
local Registry = ns:GetModule("Encounters.Registry")

local heroicCalls = {
    {
        key = "globules",
        ability = "Caustic Deluge",
        action = "SOAK ALL GLOBULES — ONE PLAYER EACH",
        warning = "SOAK ALL GLOBULES — ONE PLAYER EACH",
        voice = "Soak all globules",
        spellIDs = { 1289192 },
        prepareSeconds = 7,
        pressSeconds = 4,
    },
    {
        key = "adds",
        ability = "Venomous Emergence",
        action = "KILL ADDS — LINES AWAY FROM RAID",
        warning = "KILL ADDS — LINES AWAY FROM RAID",
        voice = "Kill adds lines away",
        spellIDs = { 1291404 },
        prepareSeconds = 8,
        pressSeconds = 5,
    },
    {
        key = "ichor",
        ability = "Coiling Ichor",
        action = "RED CIRCLES — EDGE",
        warning = "RED CIRCLES — EDGE",
        voice = "Red circles edge",
        spellIDs = { 1290809 },
        prepareSeconds = 7,
        pressSeconds = 4,
    },
    {
        key = "waves",
        ability = "Stir the Depths",
        action = "WAVES — DODGE",
        warning = "WAVES — DODGE",
        voice = "Dodge waves",
        spellIDs = { 1290956 },
        prepareSeconds = 7,
        pressSeconds = 4,
    },
    {
        key = "feast1",
        ability = "Ravenous Feast",
        action = "FEAST 1 — RAID SOAK, TANKS OUT",
        warning = "FEAST 1 — RAID SOAK, TANKS OUT",
        voice = "Feast one raid soak",
        spellIDs = { 1290516 },
        prepareSeconds = 7,
        pressSeconds = 4,
        sequenceKey = "feast",
        sequenceKeys = { "feast1", "feast2", "feast3" },
    },
    {
        key = "feast2",
        ability = "Ravenous Feast — second",
        action = "FEAST 2 — MAIN TANK SOLO",
        warning = "FEAST 2 — MAIN TANK SOLO",
        voice = "Feast two main tank",
        timing = false,
        iconSpellID = 1290516,
    },
    {
        key = "feast3",
        ability = "Ravenous Feast — third",
        action = "FEAST 3 — OFF TANK SOLO",
        warning = "FEAST 3 — OFF TANK SOLO",
        voice = "Feast three off tank",
        timing = false,
        iconSpellID = 1290516,
    },
    {
        key = "beam",
        ability = "Vile Flood",
        action = "ROTATING BEAM — CROSS EARLY, STAY BEHIND",
        warning = "ROTATING BEAM — CROSS EARLY, STAY BEHIND",
        voice = "Cross beam early",
        spellIDs = { 1294293 },
        prepareSeconds = 7,
        pressSeconds = 4,
    },
}

local mythicCalls = {
    {
        key = "adds",
        ability = "Venomous Emergence",
        action = "Kill adds; lines away",
        warning = "Adds: kill them; lines away from raid.",
        voice = "Adds",
        spellIDs = { 1291404 },
        prepareSeconds = 8,
        pressSeconds = 5,
    },
    {
        key = "globules",
        ability = "Caustic Deluge",
        action = "One player per globule",
        warning = "Globules: one player in each.",
        voice = "Globules",
        spellIDs = { 1289192 },
        prepareSeconds = 7,
        pressSeconds = 4,
    },
    {
        key = "feast",
        ability = "Ravenous Feast",
        action = "Assigned team soaks",
        warning = "Feast: assigned team soak.",
        actionTemplate = "{{rotation:feast_teams}} soak Feast",
        warningTemplate = "Feast: {{rotation:feast_teams}} soak.",
        voice = "Feast",
        spellIDs = { 1290516 },
        prepareSeconds = 7,
        pressSeconds = 4,
    },
    {
        key = "energy",
        ability = "Sanguine Storm",
        action = "Reset positions before next set",
        warning = "Reset positions; next mechanic set incoming.",
        voice = "Reset",
        spellIDs = { 1306872 },
        prepareSeconds = 7,
        pressSeconds = 4,
    },
}

Registry:Register({
    key = "twinfangs",
    name = "The Twin Fangs",
    encounterID = 3421,
    strategyStatus = "Heroic custom Feast raid→MT→OT plan with sequence-aware exact-ID guidance; BigWigs/DBM current keys source-verified 2026-09-14; Mythic remains separate; PASS-LIVE pending",
    profiles = {
        heroic = {
            explanation = {
                "SOAK 1 = RAID — TANKS OUT",
                "SOAK 2 = MAIN TANK SOLO",
                "SOAK 3 = OFF TANK SOLO",
            },
            calls = heroicCalls,
        },
        mythic = {
            explanation = {
                "Use the Mythic Feast teams and Mythic-specific venom plan; do not inherit the Heroic raid→tank→tank shortcut.",
                "Keep the three Feast assignments fresh and follow the current Mythic routing.",
            },
            calls = mythicCalls,
        },
    },
})
