local T = assert(loadfile("tests/testlib.lua"))()
local ns = T.NewNamespace()
_G.issecretvalue = function() return false end
T.Load("Core/Constants.lua", ns)
T.Load("Core/Util.lua", ns)
T.Load("Encounters/Registry.lua", ns)
T.Load("Encounters/VenomousAbyss/Sszorak.lua", ns)
local Registry = ns:GetModule("Encounters.Registry")

assert(Registry:GetProfile("sszorak", "normal") == nil)
local heroic = Registry:GetProfile("sszorak", "heroic")
assert(#heroic.explanation == 1 and heroic.explanation[1] == "{{GROUP_SPLIT:BLUE:X}}")
assert(#heroic.calls == 3)
assert(heroic.callsByKey.venom.warning == "CYSTS — PLACE AT CORRECT WIND MARK")
assert(heroic.callsByKey.venom.spellIDs[1] == 1305959)
assert(heroic.callsByKey.crosswinds.warning == "WHITE CIRCLES — STACK MID, PAIR OPPOSITE")
assert(heroic.callsByKey.crosswinds.spellIDs[1] == 1285425)
assert(heroic.callsByKey.maelstrom.warning == "WIND — POP ONE CYST")
assert(heroic.callsByKey.maelstrom.spellIDs[1] == 1285732)
assert(heroic.callsByKey.apex == nil and heroic.callsByKey.dig_in == nil,
    "Heroic must not expose old tank/damage-cooldown calls")
local mythic = Registry:GetProfile("sszorak", "mythic")
assert(mythic.callsByKey.apex and mythic.callsByKey.serpent)
print("ok - Sszorak Heroic is exactly cyst placement, Crosswinds pairing and one-cyst wind execution")
