local T = assert(loadfile("tests/testlib.lua"))()
local ns = T.NewNamespace()
_G.issecretvalue = function() return false end
T.Load("Core/Constants.lua", ns)
T.Load("Core/Util.lua", ns)
T.Load("Encounters/Registry.lua", ns)
T.Load("Encounters/AssignmentRegistry.lua", ns)
T.Load("Encounters/Boss34AssignmentOverride.lua", ns)
T.Load("Encounters/VenomousAbyss/Explorers.lua", ns)

local Registry = ns:GetModule("Encounters.Registry")
local Assignments = ns:GetModule("Encounters.AssignmentRegistry")
local encounter = Registry:Get("explorers")
local heroic = Registry:GetProfile("explorers", "heroic")
local mythic = Registry:GetProfile("explorers", "mythic")

assert(encounter and encounter.encounterID == 3497)
assert(Registry:GetProfile("explorers", "normal") == nil)
assert(table.concat(heroic.explanation, "\n") == "GEBBO → NAMA → IKU")
assert(#heroic.calls == 6)
assert(heroic.callsByKey.fish_gebbo.warning == "FISH NOW → GEBBO")
assert(heroic.callsByKey.fish_nama.warning == "FISH NOW → NAMA")
assert(heroic.callsByKey.fish_iku.warning == "FISH NOW → IKU")
assert(heroic.callsByKey.mushroom.warning == "USE MUSHROOM FOR WAVE")
assert(heroic.callsByKey.thud.warning == "SOAK MARKS")
assert(heroic.callsByKey.elements.warning == "SPREAD FIRE/FROST — CLEAR WITH OPPOSITE")
assert(heroic.callsByKey.fish_gebbo.spellIDs[1] == 1292779)
assert(heroic.callsByKey.fish_gebbo.sequenceKey == "fish")
assert(table.concat(heroic.callsByKey.fish_gebbo.sequenceKeys, ",") == "fish_gebbo,fish_nama,fish_iku")
assert(#Assignments:GetDefinitions("explorers", "heroic") == 0)
assert(#Assignments:GetDefinitions("explorers", "mythic") == 3)
assert(mythic.callsByKey.crates and mythic.callsByKey.crates.spellIDs[1] == 1291933)

print("ok - Lost Explorers Heroic uses Gebbo→Nama→Iku with six selected calls and separate Mythic crate routing")
