local T = assert(loadfile("tests/testlib.lua"))()
local ns = T.NewNamespace()
T.Load("Encounters/AssignmentRegistry.lua", ns)
T.Load("Encounters/Boss12AssignmentOverride.lua", ns)
local Registry = ns:GetModule("Encounters.AssignmentRegistry")

assert(#Registry:GetDefinitions("sentinels", "normal") == 0)
assert(#Registry:GetDefinitions("sentinels", "heroic") == 0,
    "Heroic RED/GREEN teams are generated dynamically from populated raid subgroups")
local mythic = Registry:GetDefinitions("sentinels", "mythic")
assert(#mythic == 2)
assert(mythic[1].key == "team_a" and mythic[1].label == "Green Side" and mythic[1].required)
assert(mythic[2].key == "team_b" and mythic[2].label == "Red Side" and mythic[2].required)
assert(mythic[1].callKey == "side_swap" and mythic[2].callKey == "side_swap")
assert(mythic[1].compactGroups and mythic[2].compactGroups)
print("ok - Sentinels Heroic uses dynamic RED/GREEN split while Mythic keeps explicit sides")
