local T = assert(loadfile("tests/testlib.lua"))()
local ns = T.NewNamespace()
T.Load("Encounters/AssignmentRegistry.lua", ns)
T.Load("Encounters/Boss12AssignmentOverride.lua", ns)
local Registry = ns:GetModule("Encounters.AssignmentRegistry")

assert(#Registry:GetDefinitions("nekzali", "normal") == 0)
assert(#Registry:GetLayout("nekzali", "heroic").sections == 0,
    "Heroic Nek'zali uses role-based melee+tank soak and no fixed roster assignment")
assert(#Registry:GetDefinitions("nekzali", "heroic") == 0)
local definitions = Registry:GetDefinitions("nekzali", "mythic")
assert(#definitions == 3, "Mythic Nek'zali needs Pyre plus two fresh well groups")
assert(definitions[1].key == "pyre_soakers")
assert(definitions[2].key == "well_a" and definitions[3].key == "well_b")
assert(definitions[2].rotation == "well" and definitions[3].rotation == "well")
assert(definitions[2].callKey == "grasping" and definitions[3].callKey == "grasping")
print("ok - Nek'zali Heroic has no fixed roster assignment while Mythic keeps Pyre/well assignments")
