local function read(path)
    local file = assert(io.open(path, "rb"))
    local content = assert(file:read("*a"))
    file:close()
    return content
end

local panel = read("UI/SentinelsPanel.lua")
local integration = read("Core/SentinelsIntegration.lua")
local encounter = read("Encounters/VenomousAbyss/Sentinels.lua")
local toc = read("RaidLeadAssist.toc")

assert(panel:find("GREEN %- BREATH OF ULA'TEK %- GROUPS 1%+2"))
assert(panel:find("RED %- BLOOD OF ULA'TEK %- GROUPS 3%+4"))
assert(panel:find("UnitHealth%(unit, true%)"))
assert(panel:find("UnitHealthMax%(unit%)"))
assert(panel:find("issecretvalue", 1, true))
assert(panel:find("canaccessvalue", 1, true))
assert(panel:find("SetMinMaxValues", 1, true))
assert(panel:find("SetValue", 1, true))
assert(panel:find("if secret then", 1, true))
assert(panel:find("BALANCE_THRESHOLD_PERCENT = 2", 1, true))
assert(panel:find("balanceButton", 1, true))
assert(panel:find("self.currentBalanceKey == call.key and self.balanceButton.call == call", 1, true), "unchanged balance state must not rebind/reset the button")
assert(panel:find("self.units.breath = nil", 1, true), "boss token map must clear stale Breath mappings before each refresh")
assert(panel:find("self.units.blood = nil", 1, true), "boss token map must clear stale Blood mappings before each refresh")
assert(not panel:find("SendChatMessage", 1, true))
assert(not panel:find("TargetUnit", 1, true))
assert(not panel:find("FocusUnit", 1, true))

assert(integration:find('currentEncounter.key ~= "sentinels"', 1, true))
assert(integration:find("setGenericCallsVisible", 1, true))
assert(integration:find("sentinelsPanel:SetCallState", 1, true))
assert(integration:find("sentinelsPanel:UpdateHealth", 1, true))

assert(encounter:find('warning = "KILL ADD"', 1, true))
assert(encounter:find('warning = "RUN OVER GREEN DROPLETS"', 1, true))
assert(encounter:find('warning = "SOAK CIRCLE"', 1, true))
assert(encounter:find('warning = "DISPEL DOTS"', 1, true))
assert(encounter:find('warning = "DODGE VENOM"', 1, true))
assert(encounter:find('warning = "GO TO CORNER"', 1, true))
assert(encounter:find('warning = "MATCH TO 4 > 1+3 OR 2+2"', 1, true))
assert(encounter:find('warning = "SWAP BOSS SIDES"', 1, true))
assert(encounter:find('warning = "PROTOVENOM > MARKED + MARKED"', 1, true))
assert(encounter:find('warning = "STOP DPS > BREATH OF ULA\'TEK"', 1, true))
assert(encounter:find('warning = "STOP DPS > BLOOD OF ULA\'TEK"', 1, true))
assert(encounter:find('warning = "RESUME DPS > KEEP BOTH EVEN"', 1, true))

assert(toc:find("UI/SentinelsPanel.lua", 1, true))
assert(toc:find("Core/SentinelsIntegration.lua", 1, true))

print("ok - Sentinels split UI, stable balance state, dynamic Stasis callout and secret-health display contract")
