local T = assert(loadfile("tests/testlib.lua"))()
local ns = T.NewNamespace()
_G.issecretvalue = function() return false end
T.Load("Core/Constants.lua", ns)
T.Load("Core/Util.lua", ns)
T.Load("Encounters/Registry.lua", ns)
T.Load("Encounters/VenomousAbyss/Nekzali.lua", ns)
T.Load("Encounters/VenomousAbyss/Sentinels.lua", ns)
local Registry = ns:GetModule("Encounters.Registry")

assert(Registry:GetProfile("nekzali", "normal") == nil)
local nek = Registry:GetProfile("nekzali", "heroic")
assert(#nek.explanation == 1 and nek.explanation[1] == "BL START")
assert(#nek.calls == 4)
assert(nek.calls[1].warning == "KILL ADDS")
assert(nek.calls[2].warning == "DEBUFF — GO TO THE SIDE")
assert(nek.calls[3].warning == "BURN CORPSES")
assert(nek.calls[4].warning == "MELEE + TANK — SOAK")
assert(Registry:GetProfile("nekzali", "mythic").callsByKey.grasping,
    "Mythic Nek'zali must retain the separate well mechanic")

assert(Registry:GetProfile("sentinels", "normal") == nil)
local sent = Registry:GetProfile("sentinels", "heroic")
assert(#sent.explanation == 2)
assert(sent.explanation[1] == "{{GROUP_SPLIT:RED:GREEN}}")
assert(sent.explanation[2] == "AFTER STASIS — RAID HOLDS SIDES; TANKS SWAP BOSSES")
assert(#sent.calls == 5)
assert(sent.calls[1].warning == "GREEN — SOAK DROPLETS")
assert(sent.calls[2].warning == "GREEN — KILL BLOB")
assert(sent.calls[3].warning == "GREEN — DODGE RETURN LINES")
assert(sent.calls[4].warning == "RED — GROUP SOAK, DROP BLOOD OUT")
assert(sent.calls[5].warning == "STASIS — 1+3 / 2+2")
local sentMythic = Registry:GetProfile("sentinels", "mythic")
assert(sentMythic.callsByKey.side_swap.warning == "After Stasis: hold sides; tanks swap bosses.")
assert(sentMythic.callsByKey.protovenom)

print("ok - boss 1/2 Heroic raid-lead contracts are exact and Mythic remains separate")
