local function read(path)
    local file = assert(io.open(path, "rb"))
    local content = assert(file:read("*a"))
    file:close()
    return content
end

local panel = read("UI/SentinelsPanel.lua")
local integration = read("Core/SentinelsIntegration.lua")
local encounter = read("Encounters/VenomousAbyss/Sentinels.lua")
local toc = read("RaidLeadAssist.toc")

assert(panel:find('createColumn%(instance.frame, "BREATH SIDE"'))
assert(panel:find('createColumn%(instance.frame, "BLOOD SIDE"'))
assert(panel:find("BREATH_NPC_ID = 258557", 1, true))
assert(panel:find("BLOOD_NPC_ID = 258558", 1, true))
assert(panel:find("UnitGUID%(token%)"))
assert(not panel:find("UnitName%(token%)"))
assert(panel:find("UnitHealth%(unit, true%)"))
assert(panel:find("UnitHealthMax%(unit%)"))
assert(panel:find("issecretvalue", 1, true))
assert(panel:find("canaccessvalue", 1, true))
assert(panel:find("SetMinMaxValues", 1, true))
assert(panel:find("SetValue", 1, true))
assert(panel:find("if secret then", 1, true))
assert(panel:find('createTitle%(instance.frame, "MANUAL BALANCE CALLS"'))
assert(panel:find('if call.uiGroup == "balance" then', 1, true))
assert(not panel:find("BALANCE_THRESHOLD_PERCENT", 1, true))
assert(not panel:find("UpdateBalance", 1, true))
assert(not panel:find("SetBalanceCall", 1, true))
assert(not panel:find("return percent", 1, true))
assert(not panel:find("SendChatMessage", 1, true))
assert(not panel:find("TargetUnit", 1, true))
assert(not panel:find("FocusUnit", 1, true))

assert(integration:find('currentEncounter.key ~= "sentinels"', 1, true))
assert(integration:find("setGenericCallsVisible", 1, true))
assert(integration:find("sentinelsPanel:SetCallState", 1, true))
assert(integration:find("sentinelsPanel:UpdateHealth", 1, true))

assert(encounter:find('warning = "BREATH SIDE > KILL ADD"', 1, true))
assert(encounter:find('warning = "BLOOD SIDE > SOAK TARGET"', 1, true))
assert(encounter:find('warning = "MATCH TO 4 > 1+3 OR 2+2"', 1, true))
assert(encounter:find('warning = "GROUPS HOLD SIDES > BOSSES SWAP"', 1, true))
assert(encounter:find('warning = "PROTOVENOM > MARKED + MARKED"', 1, true))
assert(encounter:find('warning = "STOP DPS > BREATH OF ULA\'TEK"', 1, true))
assert(encounter:find('warning = "STOP DPS > BLOOD OF ULA\'TEK"', 1, true))
assert(encounter:find('warning = "RESUME DPS > KEEP BOTH EVEN"', 1, true))
assert(not encounter:find('key = "balance"', 1, true))
assert(encounter:find("BOSS HP BARS ARE DISPLAY%-ONLY"))
assert(encounter:find("RAID LEADER DECIDES MANUALLY"))

assert(toc:find("UI/SentinelsPanel.lua", 1, true))
assert(toc:find("Core/SentinelsIntegration.lua", 1, true))

print("ok - Sentinels health is locale-independent display-only data with manual raidleader balance calls")
